name: Disable Workflow

on:
  workflow_dispatch:
    inputs:
      workflow_name:
        description: 'Name of the workflow to disable'
        required: true
        type: string

jobs:
  disable-workflow:
    runs-on: ubuntu-latest

    steps:
    - name: Disable specified workflow
      id: disable
      run: |
        WORKFLOW_NAME="${{ github.event.inputs.workflow_name }}"
        WORKFLOW_ID=$(gh api repos/${{ github.repository }}/actions/workflows | jq -r ".workflows[] | select(.name==\"${WORKFLOW_NAME}\") | .id")
        
        if [ -z "$WORKFLOW_ID" ]; then
          echo "Workflow with name '${WORKFLOW_NAME}' not found."
          exit 1
        fi

        gh api -X PUT repos/${{ github.repository }}/actions/workflows/${WORKFLOW_ID}/disable

    - name: Echo success message
      if: success()
      run: echo "Workflow '${{ github.event.inputs.workflow_name }}' has been successfully disabled."

    - name: Echo failure message
      if: failure()
      run: echo "Failed to disable the workflow '${{ github.event.inputs.workflow_name }}'."