
name: upload and download

on: 
  workflow_dispatch:

jobs:
  upload:
    # This job runs on Linux
    runs-on: ubuntu-latest
    
    steps:
        
      # Upload an artifact to GitHub
      - uses: actions/checkout@v3
      - name: Upload Artifact to Github Build Job
        uses: actions/upload-artifact@v4
        with:
          name: readme-artifact
          path: ./README.md

  download:
    # This job runs on Linux
    runs-on: ubuntu-latest
    needs: upload
    
    steps:
      - name: checkout
        uses: actions/checkout@v3
      # Download an artifact from GitHub
      - name: Download Artifact from Github Build Job
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.upload.outputs.readme-artifact }}
