name: Greetings

on:
  workflow_dispatch:

jobs:
  greeting:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print greeting
      run: echo "Hello, World!"
